#!/usr/bin/env python

"""
main.py
This is the main script that runs the entire AI Newsletter project.
It performs the following steps:
1. Imports functions from your other 'step' files.
2. Fetches top news articles.
3. For each article, scrapes the full text.
4. Summarizes the text using an LLM.
5. Formats all summaries into a single HTML email.
6. Sends the final email.
"""

# --- Step 1: Imports ---
print("Importing modules...")

# Import functions from your other Python files
# If you used different filenames, change the import names here.
try:
    from fetch_news import fetch_top_articles
    from step2_summarize import get_article_text, summarize_text_with_llm
    from sendgrider import send_newsletter_email
    import apikeymain
except ImportError as e:
    print(f"Error: Could not import a necessary file. {e}")
    print("Please make sure your files are named correctly:")
    print("step1_fetch.py, step2_summarize.py, step3_send_email.py, apikeymain.py")
    exit()

import time

def main():
    """
    Main function to run the newsletter generation process.
    """
    print("--- (STEP 1) FETCHING ARTICLES ---")
    
    articles = fetch_top_articles(
    api_key=apikeymain.NEWS_API_KEY,
    topic=apikeymain.TOPIC,
    domains_list=apikeymain.REPUTABLE_DOMAINS, # <-- ADD THIS LINE
    count=apikeymain.ARTICLE_COUNT
)
    
    if not articles:
        print("No articles found or API error. Exiting.")
        return

    print(f"\nSuccessfully fetched {len(articles)} articles.")
    
    # --- Step 2: Summarizing Articles ---
    print("\n--- (STEP 2) SCRAPING AND SUMMARIZING ---")
    
    # Start building the HTML for the email
    html_content = f"""
    <html>
      <head>
        <style>
          body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
          h1 {{ color: #333; }}
          li {{ margin-bottom: 20px; padding: 10px; border: 1px solid #ddd; border-radius: 5px; }}
          a {{ color: #0066cc; }}
        </style>
      </head>
      <body>
        <h1>Your AI-Powered News Digest for "{apikeymain.TOPIC}"</h1>
        <ul>
    """
    
    summaries = []
    
    for i, article in enumerate(articles):
        print(f"\nProcessing article {i+1}: {article['title']}")
        
        # Scrape the full text from the article URL
        full_text = get_article_text(article['url'])
        
        if not full_text:
            print(f"  Warning: Could not scrape full text. Using description as fallback.")
            summary = article['description'] + " (Summary not available - using snippet.)"
        else:
            print("  Scraping complete. Generating summary...")
            # Summarize the text
            summary = summarize_text_with_llm(full_text)
        
        print(f"  Summary: {summary[:100]}...") # Print first 100 chars of summary
        
        # Add this article to our HTML email
        html_content += f"""
          <li>
            <b><a href="{article['url']}" target="_blank">{article['title']}</a></b><br>
            <small>Source: {article['source']['name']}</small><br><br>
            {summary}
          </li>
        """
        
        # Be nice to the APIs, wait a second before the next request
        time.sleep(1) 

    # Close the HTML tags
    html_content += """
        </ul>
        <p><i>This newsletter was automatically generated by a Python script.</i></p>
      </body>
    </html>
    """
    
    # --- Step 3: Sending Email ---
    print("\n--- (STEP 3) SENDING EMAIL ---")
    
    send_newsletter_email(
        recipient=apikeymain.RECIPIENT_EMAIL,
        email_content_html=html_content
    )
    
    print("\n--- PROCESS COMPLETE ---")

# This makes sure the 'main()' function is called only when you
# run this script directly (e.g., `python main.py`)
if __name__ == "__main__":
    main()